IMGTFS/Controllers/VisaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.OleDb;
using System.Web;
using System.Web.Mvc;
using System.Xml;
using IMG_BusinessServices;
using BusinessServices;
using IMG_BusinessEntities;
using IMG_DataModel;
using System.Data.SqlClient;
using IMGTFS.Filters;


namespace IMG_TFS.Controllers
{
   
    public class VisaController : Controller
    {

        private IUploadFileService _uploadFileService;
        private IVisaCardService _visaCardService;
        public VisaController(IUploadFileService _uploadFileService, IVisaCardService _visaCardService)
        {
            this._uploadFileService = _uploadFileService;
            this._visaCardService = _visaCardService;
           
        }

      

        public ActionResult UploadExcelFile()
        {
            return View();
        }
        // GET: /Visa/
         [CustomAuthAttribute(Department = "agentSupport")]
         [HttpPost]
        public ActionResult ProcessExcelFile(HttpPostedFileBase NAMEbtnUpload)
        {
            DataSet ds = new DataSet();
            string excelConnectionString = null;
             String[] ExcelSheetNames = new String[0];
             try
             {
                 if (NAMEbtnUpload.ContentLength > 0) 
                 {
                     string fileExtension = System.IO.Path.GetExtension(Request.Files["NAMEbtnUpload"].FileName);
                     string fileLocation = FileLocation(fileExtension);

                     excelConnectionString = _uploadFileService.GetExcelConnection(fileLocation, fileExtension);
                     if (excelConnectionString != "ods")
                     {
                         OleDbConnection oleDbExcelCon = null;
                         try
                         {
                             oleDbExcelCon = _uploadFileService.GetOleDbConnection(excelConnectionString);
                             ExcelSheetNames = _uploadFileService.getTableNames(oleDbExcelCon, excelConnectionString);
                             oleDbExcelCon.Close();
                         }
                         catch (Exception e)
                         {
                             Response.Write("<script>alert('" + Server.HtmlEncode(e.Message) + "')</script>");
                             Console.WriteLine(e);
                         }


                         UploadFile(fileExtension, ds);
                         TempData["SheetNames"] = ExcelSheetNames;
                     }

                 }
               
             }catch(Exception e){
                 Console.WriteLine(e);
                 //return RedirectToAction("AgentSupport");
             }

             return RedirectToAction("ProcessExcelSheet", new { ExcelConnString = excelConnectionString });
        }


         public ActionResult Visa()
         {
             return View();
         }

         
         public ActionResult ProcessExcelSheet(string ExcelConnString)
         {
             if (ExcelConnString == "ods") {
                 ViewBag.ods = "yes";
             }
             else
             {
                 var ExcelShtNames = (string[])TempData["SheetNames"];
                 Session["conn"] = ExcelConnString;
                 ViewBag.selection = ExcelShtNames;
                 int ExcelShtNamesLength = ExcelShtNames.Length;
                 if (ExcelShtNamesLength == 0)
                 {
                     ViewBag.NoSheetName = "yes";
                 }
             }
             return View();
         }

         [CustomAuthAttribute(Department = "agentSupport")]
         public ActionResult AgentSupport()
         {
            
             return View();
         }

         [CustomAuthAttribute(Department = "agentSupport")]
         public ActionResult Renewal()
         {
             return View();
         }


         public ActionResult ApplicationDetails()
         {
             return View();
         }

         [CustomAuthAttribute(Department = "agentSupport")]
         public ActionResult EditDetails()
         {
             return View();
         }

         public ActionResult AccountingVerification()
         {
             return View();
         }
         public ActionResult DisplayExcelContents(string RadioButtonSheetSelect)
         {
             List<VisaCard> visaCardList = new List<VisaCard>();
             if (RadioButtonSheetSelect != null)
             {
                 DataSet ds = new DataSet();
              
                 string myConnectionStr = Session["conn"] as String;
                 ds = _uploadFileService.queryExcelTables(myConnectionStr, RadioButtonSheetSelect);

                

                 for (int i = 0; i < ds.Tables[0].Rows.Count; i++)
                 {

                     if (!string.IsNullOrWhiteSpace(ds.Tables[0].Rows[i][4].ToString()))
                     {
                        

                         VisaCard visaCard = new VisaCard
                         {
                             Account_No = ds.Tables[0].Rows[i][3].ToString(),
                             AgentCode = ds.Tables[0].Rows[i][4].ToString(),
                             LastName = ds.Tables[0].Rows[i][5].ToString(),
                             FirstName = ds.Tables[0].Rows[i][6].ToString(),
                             Addr1 = ds.Tables[0].Rows[i][7].ToString(),
                             Phone1 = ds.Tables[0].Rows[i][11].ToString(),
                             Phone2 = ds.Tables[0].Rows[i][12].ToString(),
                             Sex = ds.Tables[0].Rows[i][13].ToString(),
                             Birthday = ds.Tables[0].Rows[i][14].ToString(), 
                             TITLE_CODE = ds.Tables[0].Rows[i][33].ToString(),
                             MotherMaidenName = ds.Tables[0].Rows[i][34].ToString(),
                             MiddleName = ds.Tables[0].Rows[i][35].ToString(),
                             Birthplace = ds.Tables[0].Rows[i][36].ToString(),
                             MaritalStatus = ds.Tables[0].Rows[i][37].ToString(),
                             SpouseName = ds.Tables[0].Rows[i][38].ToString(),
                             PERMANENT_ADD1 = ds.Tables[0].Rows[i][41].ToString(),
                             ID_TYPE = ds.Tables[0].Rows[i][44].ToString(),
                             ID_NO = ds.Tables[0].Rows[i][45].ToString(),
                             TIN = ds.Tables[0].Rows[i][48].ToString(),
                             SSS = ds.Tables[0].Rows[i][49].ToString(),
                             OccupationDesc = ds.Tables[0].Rows[i][50].ToString(),
                             OccupationCode = ds.Tables[0].Rows[i][51].ToString(),
                             CurrentEmployer = ds.Tables[0].Rows[i][52].ToString(),
                             Nationality = ds.Tables[0].Rows[i][56].ToString(),
                             SourceOfFunds = ds.Tables[0].Rows[i][57].ToString(),
                         };
                         visaCardList.Add(visaCard);
                     }
                 }
               
               
             }
            List<VisaCard> listOfExistingAgentCodes = _visaCardService.CheckIfAgentCodeAlreadyExists(visaCardList);
            List<VisaCard> listOfNewVCApplication =  new List<VisaCard>();
            if (listOfExistingAgentCodes.Count != 0)
            {
                listOfNewVCApplication = _visaCardService.filterAgentCodes(listOfExistingAgentCodes, visaCardList);
                ViewBag.ListOfExistingAgents = "List of Existing Agents";              
            }
            else
            {
                listOfNewVCApplication.AddRange(visaCardList);
            }

            int noOfRowsAffected = _visaCardService.SaveListOfNewMember(listOfNewVCApplication);
            ViewBag.listOfAgentCodes = listOfExistingAgentCodes;
            ViewBag.list = listOfNewVCApplication;
         
            return View();
         }


         [CustomAuthAttribute(Department = "agentSupport")]
         public ActionResult NewMembership()
         {
             return View();
         }


         public ActionResult SaveContentsOfExcelFile(List<VisaCard> listOfitems)
         {
           
             ViewBag.Name = listOfitems[0];
             return View();
         }

         public ActionResult VisaApplicationStatusReport()
         {
             return View();
         }

         [CustomAuthAttribute(Department = "agentSupport")]
         public ActionResult CashCardApplication(FormCollection collection)
         {
             int noOfRowsAffected = 0;
             string firstName = collection["firstName"];
             string lastName = collection["lastName"];
             string middleName = collection["middleName"];
             string phoneNo = collection["phoneNo"];
             string contactNo = collection["contactNo"];
             string dateOfBirth = collection["dateOfBirth"];
             string placeOfBirth = collection["placeOfBirth"];
             string nationality = collection["nationality"];
             string emailAddress = collection["emailAddress"];
             string presentAddress = collection["presentAddress"];
             string countryOfOrigin = collection["countryOfOrigin"];
             string permanentAddress = collection["permanentAddress"];
             string idPresented = collection["idPresented"];
             string idNo = collection["idNo"];
             string nameOfEmployer = collection["nameOfEmployer"];
             string natureOfWork = collection["natureOfWork"];
             string natureOfEmployeeBusiness = collection["natureOfEmployeeBusiness"];
             string sourceOfFunds = collection["sourceOfFunds"];
             string remettersName = collection["remettersName"];

             VisaCard visaCard = new VisaCard
             {
                 
                 LastName = lastName,
                 FirstName = firstName,

IMGTFS/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Total Financial Solutions</title>

    <link href="~/Content/bootstrap.css" rel="stylesheet" type="text/css">
    <script src="~/Scripts/jquery-2.2.0.min.js"></script>
    <link href="~/css/loginCss.css" rel="stylesheet" />
    <script src="~/js/HomeScript.js"></script>
   <!--new Theme for navbar-->
    <link href="~/css/font-awesome.min.css" rel="stylesheet" type="text/css"/>  
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />    
    <link href="~/css/theme.css" rel="stylesheet" type="text/css" />
    <link href="~/css/MyStyles.css" rel="stylesheet" type="text/css" />
 

    <!--datepicker-->
    <link href="~/css/datepicker.css" rel="stylesheet" type="text/css">
   

    <!--dataTables-->
    <link rel="stylesheet" type="text/css" href="~/Content/DataTables/css/jquery.dataTables.css">
    <link rel="stylesheet" type="text/css" href="~/Content/DataTables/css/jquery.dataTables_themeroller.css">
    <script type="text/javascript" charset="utf8" src="~/Scripts/DataTables/jquery.dataTables.min.js"></script>
    <link rel="stylesheet" type="text/css" href="~/Content/DataTables/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" type="text/css" href="~/Content/DataTables/css/buttons.dataTables.min.css" />

    <script src="~/Scripts/DataTables/dataTables.buttons.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.flash.min.js"></script>
    <script src="~/js/jszip.min.js"></script>
    <script src="~/js/pdfmake.min.js"></script>
    <script src="~/js/vfs_fonts.js"></script>
    <script src="~/Scripts/DataTables/buttons.html5.min.js"></script>
    <script src="~/Scripts/DataTables/buttons.print.min.js"></script>
    <script src="~/Scripts/dataTables.tableTools.js"></script>

    <script type="text/javascript" src="~/js/dataTablesScript.js"></script>

    <link href="~/css/dataTablesStyles.css" rel="stylesheet" type="text/css" />
    <link href="~/css/visaCssStyles.css" rel="stylesheet" type="text/css" />
    <link href="~/css/SideMenuStyles.css" rel="stylesheet" type="text/css" />
</head>
<body>
   

    <nav class="navbar navbar-default navbar-inverse img-navbar navbar-fixed-top" role="navigation">
        <div class="container-fluid">
           
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a id="homePageLink" class="brand" href="@Url.Action("Home", "Home")">
                        <img src="~/images/IMG_logo.png" class="img-logo">
                        <div class="s-m-left img-logo-name">International<br>Marketing<br>Group</div>
                    </a>
                </div>
           
            <div id="headerLinks">
                <div class="collapse navbar-collapse navbar-ex1-collapse">

                    <ul class="nav navbar-nav navbar-right">
                        <li><a href="@Url.Action("Home", "Home")"><i class="fa fa-home"></i> Home</a></li>
                       
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-line-chart"></i> Investments <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                               
                                <li><a href="@Url.Action("MAA_MUTUAL_LIFE", "Investments")">MAA Mutual Life</a></li>
                               
                                <li><a href="@Url.Action("Invest", "Investments", new { investmentType = "FAMI" })">FAMI</a></li>

                                <li><a href="@Url.Action("SOLDIVO", "Investments")">SOLDIVO</a></li>
                              
                                <li><a href="@Url.Action("Invest", "Investments", new { investmentType = "PRUDENTIAL_OPTIMA" })">PRUDENTIAL OPTIMA</a></li>
                               
                                <li><a href="@Url.Action("Invest", "Investments", new { investmentType = "PAMI" })">PAMI</a></li>
                              
                                <li><a href="@Url.Action("Invest", "Investments", new { investmentType = "COCO_LIFE" })">COCO LIFE</a></li>

                                <li><a href="@Url.Action("Invest", "Investments", new { investmentType = "ATR_KIMENG" })">ATR KIMENG</a></li>
                           
                                <li class="dropdown-submenu pull-left">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Phil Equity</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="#">PhilEquity Dividend Yield Fund</a></li>
                                        <li><a href="#">PhilEquity Dollar Income Fund</a></li>
                                        <li><a href="#">PhilEquity Fund</a></li>
                                        <li><a href="#">PhilEquity Money Market Fund</a></li>
                                        <li><a href="#">PhilEquity Peso Bond Fund</a></li>
                                        <li><a href="#">PhilEquity PSE Index Fund</a></li>
                                    </ul>
                                </li>

                             </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-gift"></i> Executive Bonus <span class="caret"></span></a>
                            <ul class="dropdown-menu">

                                <li><a href="@Url.Action("PolicyMaster", "FinancialSolution")">Executive Policy Master</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("ExecBonus", "FinancialSolution")">Bonus Pooling</a></li>
                            </ul>
                        </li>

                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-file-text-o"></i> Reports <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                                  
                                @*<li><a href="@Url.Action("SOLDIVO", "Investments")">SOLDIVO</a></li>*@

                                <li class="dropdown-submenu pull-left">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">SOLDIVO</a>
                                    <ul class="dropdown-menu">
                                        <li><a href="@Url.Action("SoldivoTransmittal", "Investments", new {fund = "SOLDIVO BOND FUND INC" })">Soldivo Bond Fund Inc</a></li>
                                        <li><a href="@Url.Action("SoldivoTransmittal", "Investments", new {fund = "SOLDIVO STRATEGIC GROWTH FUND INC" })">Soldivo Strategic Growth Fund Inc</a></li>

                                    </ul>   
                               </li>      
                                        <li><a href="@Url.Action("Invest", "Investments", new { investmentType = "ATR_KIMENG" })">ATR KIMENG</a></li>

                                        <li class="dropdown-submenu pull-left">
                                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Phil Equity</a>
                                            <ul class="dropdown-menu">
                                                <li><a href="@Url.Action("PhilEquityTransmittal", "Investments", new {fund = "PHILEQUITY DIVIDEND YIELD FUND" })">PhilEquity Dividend Yield Fund</a></li>
                                                <li><a href="@Url.Action("PhilEquityTransmittal", "Investments", new {fund = "PHILEQUITY DOLLAR INCOME FUND"})">PhilEquity Dollar Income Fund</a></li>
                                                <li><a href="@Url.Action("PhilEquityTransmittal", "Investments", new {fund = "PHILEQUITY FUND" })">PhilEquity Fund</a></li>
                                                <li><a href="@Url.Action("PhilEquityTransmittal", "Investments", new {fund = "PHILEQUITY MONEY MARKET FUND" })">PhilEquity Money Market Fund</a></li>
                                                <li><a href="@Url.Action("PhilEquityTransmittal", "Investments", new {fund = "PHILEQUITY PESO BOND FUND" })">PhilEquity Peso Bond Fund</a></li>
                                                <li><a href="@Url.Action("PhilEquityTransmittal", "Investments", new {fund = "PHILEQUITY PSE INDEX FUND" })">PhilEquity PSE Index Fund</a></li>
                                            </ul>
                                        </li>

                            </ul>
                        </li>
                        @*<li><a href="@Url.Action("AgentSupport", "Visa")"><i class="fa fa-cc-visa"></i> Visa Tracking </a></li>*@
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><i class="fa fa-cc-visa"></i> Visa Card Tracking <span class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="@Url.Action("AgentSupport", "Visa")">Agent Support</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Finance", "Visa")">Finance</a></li>
                                <li role="separator" class="divider"></li>
                                <li><a href="@Url.Action("Accounting", "Visa")">Accounting Verification</a></li>
                            </ul>
                        </li>
                        <li><a href="@Url.Action("login","Login")"><i class="fa fa-sign-out"></i> Logout</a></li>
                        
                    </ul>
                </div><!-- /.navbar-collapse -->
            </div>
         </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>
    @*<div id="footer">
        <footer>
            <p>&copy; @DateTime.Now.Year - IMG Total Financial Solutions</p>
        </footer>
    </div>*@
    <script src="~/Scripts/bootstrap.min.js"></script>
    <script src="~/Scripts/bootstrap-datepicker.js"></script>
   

    <!--Must be placed before bootstrap-datepicker.js -->
    <script type="text/javascript">
        $(document).ready(function () {

            $('.input-daterange').datepicker({
                todayBtn: "linked"
            });
        });
    </script>
</body>
</html>